// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfU0FvHfoG0uvCcETG6pWr8xUZtNSBix0',
    appId: '1:889463869810:web:602ed1768d364c234b0deb',
    messagingSenderId: '889463869810',
    projectId: 'bbm-db-dev',
    authDomain: 'bbm-db-dev.firebaseapp.com',
    databaseURL: 'https://bbm-db-dev-default-rtdb.firebaseio.com',
    storageBucket: 'bbm-db-dev.firebasestorage.app',
    measurementId: 'G-4EPSS33GB9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC29QXZDOgpVWDr7gfo8_a1xLPYLI_7TQE',
    appId: '1:889463869810:android:169d01af762a94b04b0deb',
    messagingSenderId: '889463869810',
    projectId: 'bbm-db-dev',
    databaseURL: 'https://bbm-db-dev-default-rtdb.firebaseio.com',
    storageBucket: 'bbm-db-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Z4aYJUgVqFUPoVyqGfIFyRrlEzu3gUk',
    appId: '1:889463869810:ios:526564e8b512ce8b4b0deb',
    messagingSenderId: '889463869810',
    projectId: 'bbm-db-dev',
    databaseURL: 'https://bbm-db-dev-default-rtdb.firebaseio.com',
    storageBucket: 'bbm-db-dev.firebasestorage.app',
    iosBundleId: 'com.example.demoIosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Z4aYJUgVqFUPoVyqGfIFyRrlEzu3gUk',
    appId: '1:889463869810:ios:526564e8b512ce8b4b0deb',
    messagingSenderId: '889463869810',
    projectId: 'bbm-db-dev',
    databaseURL: 'https://bbm-db-dev-default-rtdb.firebaseio.com',
    storageBucket: 'bbm-db-dev.firebasestorage.app',
    iosBundleId: 'com.example.demoIosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfU0FvHfoG0uvCcETG6pWr8xUZtNSBix0',
    appId: '1:889463869810:web:cd0abddc9c4aee254b0deb',
    messagingSenderId: '889463869810',
    projectId: 'bbm-db-dev',
    authDomain: 'bbm-db-dev.firebaseapp.com',
    databaseURL: 'https://bbm-db-dev-default-rtdb.firebaseio.com',
    storageBucket: 'bbm-db-dev.firebasestorage.app',
    measurementId: 'G-BCT1225YNN',
  );
}
